# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ReactiveCocoaUse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactiveCocoaUse

  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'NIMSDK', :path => './frameworks/NIMSDK'
  pod 'QYSDK', :path => './frameworks/QYSDK'
  target 'ReactiveCocoaUseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveCocoaUseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
